export const data = [
  {
    invoiceId: 1001,
    invoiceDate: '2025-07-01',
    invoiceNumber: 'INV-001',
    dueDate: '2025-07-10',
    supplierName: 'Alpha Supplies',
    accountHead: 'Office Supplies',
    description: 'Stationery purchase',
    amount: 200.0,
    gst: 20.0,
    totalAmount: 220.0,
    paymentDate: '2025-07-05',
    preview: true,
    siteName: 'BP LAWNTON',
    directDebit: 'Yes',
    paymentType: 'CASH',
    invoiceType: 'Original'
  },
  {
    invoiceId: 1002,
    invoiceDate: '2025-07-02',
    invoiceNumber: 'INV-002',
    dueDate: '2025-07-12',
    supplierName: 'Beta Hardware',
    accountHead: 'Maintenance',
    description: 'Repair tools',
    amount: 150.0,
    gst: 15.0,
    totalAmount: 165.0,
    paymentDate: '2025-07-06',
    preview: false,
    siteName: 'BP HIGHFIELDS',
    directDebit: 'No',
    paymentType: 'CARD',
    invoiceType: 'Dummy'
  },
  {
    invoiceId: 1003,
    invoiceDate: '2025-07-03',
    invoiceNumber: 'INV-003',
    dueDate: '2025-07-13',
    supplierName: 'Gamma Tech',
    accountHead: 'IT Equipment',
    description: 'Laptop purchase',
    amount: 1200.0,
    gst: 120.0,
    totalAmount: 1320.0,
    paymentDate: '2025-07-08',
    preview: true,
    siteName: 'BP LAWNTON',
    directDebit: 'Yes',
    paymentType: 'CARD',
    invoiceType: 'Original'
  },
  {
    invoiceId: 1004,
    invoiceDate: '2025-07-04',
    invoiceNumber: 'INV-004',
    dueDate: '2025-07-14',
    supplierName: 'Delta Print',
    accountHead: 'Printing',
    description: 'Marketing flyers',
    amount: 300.0,
    gst: 30.0,
    totalAmount: 330.0,
    paymentDate: '2025-07-09',
    preview: false,
    siteName: 'BP HIGHFIELDS',
    directDebit: 'No',
    paymentType: 'CASH',
    invoiceType: 'Dummy'
  },
  {
    invoiceId: 1005,
    invoiceDate: '2025-07-05',
    invoiceNumber: 'INV-005',
    dueDate: '2025-07-15',
    supplierName: 'Omega Logistics',
    accountHead: 'Logistics',
    description: 'Courier charges',
    amount: 180.0,
    gst: 18.0,
    totalAmount: 198.0,
    paymentDate: '2025-07-10',
    preview: false,
    siteName: 'BP LAWNTON',
    directDebit: 'Yes',
    paymentType: 'CARD',
    invoiceType: 'Original'
  },
  {
    invoiceId: 1006,
    invoiceDate: '2025-07-06',
    invoiceNumber: 'INV-006',
    dueDate: '2025-07-16',
    supplierName: 'Sigma Cleaners',
    accountHead: 'Facility Management',
    description: 'Office cleaning',
    amount: 250.0,
    gst: 25.0,
    totalAmount: 275.0,
    paymentDate: '2025-07-11',
    preview: true,
    siteName: 'BP HIGHFIELDS',
    directDebit: 'No',
    paymentType: 'CASH',
    invoiceType: 'Dummy'
  },
  {
    invoiceId: 1007,
    invoiceDate: '2025-07-07',
    invoiceNumber: 'INV-007',
    dueDate: '2025-07-17',
    supplierName: 'Zeta Networks',
    accountHead: 'Internet Services',
    description: 'Monthly broadband',
    amount: 100.0,
    gst: 10.0,
    totalAmount: 110.0,
    paymentDate: '2025-07-12',
    preview: true,
    siteName: 'BP LAWNTON',
    directDebit: 'Yes',
    paymentType: 'CASH',
    invoiceType: 'Original'
  },
  {
    invoiceId: 1008,
    invoiceDate: '2025-07-08',
    invoiceNumber: 'INV-008',
    dueDate: '2025-07-18',
    supplierName: 'Theta Travel',
    accountHead: 'Travel',
    description: 'Client visit travel',
    amount: 500.0,
    gst: 50.0,
    totalAmount: 550.0,
    paymentDate: '2025-07-13',
    preview: true,
    siteName: 'BP HIGHFIELDS',
    directDebit: 'No',
    paymentType: 'CARD',
    invoiceType: 'Dummy'
  },
  {
    invoiceId: 1009,
    invoiceDate: '2025-07-09',
    invoiceNumber: 'INV-009',
    dueDate: '2025-07-19',
    supplierName: 'Lambda Media',
    accountHead: 'Advertising',
    description: 'Social media ads',
    amount: 400.0,
    gst: 40.0,
    totalAmount: 440.0,
    paymentDate: '2025-07-14',
    preview: true,
    siteName: 'BP LAWNTON',
    directDebit: 'Yes',
    paymentType: 'CASH',
    invoiceType: 'Original'
  },
  {
    invoiceId: 1010,
    invoiceDate: '2025-07-10',
    invoiceNumber: 'INV-010',
    dueDate: '2025-07-20',
    supplierName: 'Nova Legal',
    accountHead: 'Legal',
    description: 'Contract review',
    amount: 1000.0,
    gst: 100.0,
    totalAmount: 8100.0,
    paymentDate: '2025-07-15',
    preview: true,
    siteName: 'BP HIGHFIELDS',
    directDebit: 'No',
    paymentType: 'CARD',
    invoiceType: 'Dummy'
  }
];
